# Generated by Django 2.0.3 on 2018-07-27 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_code_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.IntegerField(unique=True)),
                ('contributors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
