# Generated by Django 2.0.3 on 2018-07-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral_code_to_user',
            old_name='referral_code',
            new_name='ajo_code',
        ),
    ]
