# Generated by Django 2.0.3 on 2018-07-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_referral_code_to_user_money_to_be_contributed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral_code_to_user',
            name='contributors',
        ),
        migrations.DeleteModel(
            name='Referral_code_to_user',
        ),
    ]
