# Generated by Django 2.0.3 on 2018-07-28 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_ajo_group_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Dashboard_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ajo_group_details',
            name='ajo_code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='user_dashboard_details',
            name='ajo_groups',
            field=models.ManyToManyField(to='home.Ajo_Group_Details'),
        ),
        migrations.AddField(
            model_name='user_dashboard_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
